VERILATOR := verilator
VERILATOR_ROOT := /usr/share/verilator
VERILATOR_INCLUDE := $(VERILATOR_ROOT)/include

CC := g++
CC_FLAGS := -Wall -Wextra -Werror -faligned-new

IVERILOG_COMPILE := iverilog
IVERILOG_SIMULATE := vvp
